#!/bin/bash
set -e

case "$1" in
  remove|deconfigure)
    echo "Removing RemoteCompanion..."
    ;;
  upgrade|failed-upgrade)
    ;;
  *)
    echo "prerm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0
